### ISSUE TITLE
Crash since 2017

### ISSUE THREAD

**Issue by sergeevabc** [aegoroff/hc#193]
Core2Duo with SSE, 4 GB RAM, no dedicated GPU, Windows 7 x64.

[5.0.0-beta][1] (hc.5.0.421.0.x64.zip) works fine, later versions cause a crash as follows

``` console
$ hc.exe 
An unhandled exception occurred. Dump saved to: hc.exe.dmp
```

Why?

[1]: https://github.com/aegoroff/hc/releases/tag/v5.0.0-beta

**Comment by aegoroff** [comment]
sorry but minimum supported processor is haswell, Core2Duo is too old.

**Comment by aegoroff** [comment]
strictly speaking you have to support SSE4.2 in your proccessor (https://en.wikipedia.org/wiki/SSE4) where crc32 instructions set appeared first. The first processor with this instructions set was Intel Core 1st gen (Nehalem), but i decided to restrict minimum supported version to Intel Core 4th gen (Haswell) because it's rather old processor too.

**Comment by sergeevabc** [comment]
Признаться, Александр, я удивлён этим подходом.

Вычисление контрольной суммы это математическая задача, решение которой _можно ускорить_ с помощью железа, но можно решить и чуть медленнее на железе без соответствующих инструкций процессора. Например, отечественный консольный калькулятор [RHash][1] и иностранный графический [RapidCRC][2] позволяют вычислить CRC32C без проблем. Более того, отлично вычисляются значения, используя и более современные алгоритмы вроде xxHash и Blake3.

``` console
$ rhash --crc32c img202405*.jpg
a446184e  img202405_6894.jpg
b0b12552  img202405_6895.jpg
9be4c0f0  img202405_6896.jpg

$ b3sum img202405*.jpg
96ac12a2716c7c25b00380017aebc56b78602e484a2ecb2b80c1961bcfdc0598  img202405_6894.jpg
c4b824e925f627d3afe34c3a04ed769b0ae73ab0ac08c8312f161c2eda38cbcb  img202405_6895.jpg
3614a0d0afa46fb6eeb921a7eded0d602a433e898baf710c09740869ed870633  img202405_6896.jpg
```

![2024-0510-1257 rapidcrc crc32c blake3](https://github.com/aegoroff/hc/assets/373718/3943fc4d-d213-4b33-b36b-6a4aa08fb18f)

[1]: https://rhash.sourceforge.io/
[2]: https://www.ov2.eu/programs/rapidcrc-unicode

**Comment by aegoroff** [comment]
Привет, - я просто не вижу смысла в поддержке старого железа и все. Кроме того, в новых процессорах намного больше и других полезных инструкций, позволяющих ускоряться. Как то так. Ну а вообще да, несложно это в софте сделать. Фраза же "но можно решить и чуть медленнее на железе без соответствующих инструкций процессора" не соответствует действительности - прирост, не "чуть быстрее", а в в 10 раз быстрее, т.е. на порядок, по сравнению с софтовой реализацией.

**Comment by aegoroff** [comment]
Дополню - вон вроде даже та же Windows 10, насколько я помню, уже тоже требует минимум процессор Haswell. А та же Windows 7 уже не поддерживается самим майкрософт.

**Comment by aegoroff** [comment]
Еще дополню, - про ускорение в 10 раз я тоже наврал, - всего в 2 раза
сrc32 (вычисляется софтом)
```
DJI_0048.mov | 18.77 Gb (20158525443 bytes) | 4.503 sec | 71DFD910
DJI_0046.mov | 14.51 Gb (15584987331 bytes) | 3.475 sec | 3F4AB344
DJI_0044.mov | 32.86 Gb (35281060299 bytes) | 7.848 sec | 30FC2A11
```
сrc32c (вычисляется железом)
```
DJI_0048.mov | 18.77 Gb (20158525443 bytes) | 2.534 sec | AE0939C5
DJI_0046.mov | 14.51 Gb (15584987331 bytes) | 1.952 sec | 7BDFD569
DJI_0044.mov | 32.86 Gb (35281060299 bytes) | 4.435 sec | 8C2DF92D
```
кэщ файловой системы прогрет и запускал несколько раз

**Comment by sergeevabc** [comment]
Майкрософт это коммерческая компания, чьи решения продиктованы прибылью, а не стремлением сделать мир лучше. Исповедуя худшие практики капитализма вроде [искусственного устаревания][1], они трубят об отмене поддержки того или иногда продукта, чтобы люди, подсаженные на иглу еженедельных обновлений и позабывших, что вообще-то у продукта возможно состояние «достаточно совершенен», испугались и побежали покупать что-то революционное.

А революционное ли? Если раньше — при смене Windows — мы видели технологические прорывы вроде перехода на 64 бита, расширение оперативной памяти за 4 ГБ и более устойчивую файловую систему NTFS, то Windows 10, а тем более 11, это функционально-эстетический кошмар, отражающий разложение Запада, где директора Mozilla выгнали из-за консервативных взглядов на семью и Silicon Valley Bank рухнул из-за того, что начальница по управлению рисками занималась не своим делом, а «радужными» проектами. Эти новые ОС сделаны наспех лишь бы сделать, на фоне чего Windows 7 это тот самый надёжный молоток из времён «когда трава была зеленее», который продолжает забивать гвозди, не смотря на истёкшую гарантию.

Более того, смотря шире, можно увидеть (и всегда надо помнить про) огромный разрыв в потреблении в разных уголках не то, что планеты, но даже России — на том же Мадагаскаре только у 600 000 из 5 800 000 есть доступ к электричеству, на обложенной санкциями Кубе люди ездят на автомобилях многолетней давности, в сельских школах Индии компьютеры собирают из б/у запчастей, купленных на Алиэкспрессе, а после наводнения в Оренбурге тысячи семей явно будут рады и винтажному ноутбуку, а не побегут покупать новый за 50-100 тысяч рублей. Если же спросить у Гугла, сколько планет потребуется, чтобы все жили, как зажиточные американцы (а не те миллионы бедняг, что выживают на продуктовых карточках), то Гугл ответит: 5! А у нас всего одна Земля, Александр, т.е. не все могут иметь по несколько велосипедов, машин, домов, и в т.ч. регулярно обновлять компьютерное железо.

Жизнь при этом полна тягот, как и прежде, и чтобы их облегчить, технологии нужно делать доступнее, буквально приносить их в каждый дом, а не сохранять их уделом лишь условного золотого миллиарда. Сегодня этой героической цели, когда компьютеры вышли из огромных залов и очутились на ладони, может посодействовать любой человек, называющий себя программистом.

В частности, калькулятор контрольных сумм это тот инструмент, благодаря которому ты спокойнее спишь, зная, что файл передан и сохранён без случайных или намеренных повреждений. Что поддерживать в этом калькуляторе, чтобы он долгие-долгие годы служил как можно большему числу людей? Алгоритм не меняется, функция оперирования с файлами меняется крайне редко. Например, [FairStair HashFiles][2] позволяет посчитать SHA256 даже на Windows 98, в чём я только что убедился, установив его в виртуальной машине. Да-да, Александр, даже эту ОС [до сих пор используют][3], не то что Windows 7.

[1]: https://ru.wikipedia.org/wiki/%D0%9F%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D1%83%D0%B5%D0%BC%D0%BE%D0%B5_%D1%83%D1%81%D1%82%D0%B0%D1%80%D0%B5%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
[2]: http://www.fairstars.com/hashfiles/
[3]: https://forum.ru-board.com/topic.cgi?forum=62&topic=31624&start=640

**Comment by sergeevabc** [comment]
Пожалуйста, сделайте билд для старых процессоров (где потолок это SSE3), это же вопрос флагов при компиляции. Его достаточно выкладывать раз в год, всё равно хэш-алгоритмы появляются редко. Никакой поддержки этого билда не требуется, никто же не просит вагоны с углём разгружать.

**Comment by aegoroff** [comment]
> Пожалуйста, сделайте билд для старых процессоров (где потолок это SSE3), это же вопрос флагов при компиляции. Домашний сервер стоит в кладовке, в нём только жёсткий диск меняется, на котором надо считать хэши. Такой билд достаточно выкладывать раз в год, всё равно алгоритмы появляются редко. Никакой поддержки этого билда не требуется, никто же не просит вагоны с углём разгружать.

я боюсь что не все так просто

1. Не знаю возможно ли компилировать CUDA SDK для столь старых процессоров.
2. Не знаю будет ли zig компилятор нормально делать код для этого, тут скорее да чем нет
3. Для sha1, md5 и еще кое чего использована библиотека OpenSSL 3.4.1 и там для этого все это делается через ручные реализации на ассемблере. Чтобы это отключать для старых процессоров придется через макросы корячить исходники
4. Аналогично п.3 ассемблер использован для алгоритма blake3 - там тоже надо будет корячить исходники

все это требует немалых сил и времени

**Comment by sergeevabc** [comment]
[Zig](https://ziglang.org/)? У меня Гитхаб показывает, что ваша программа написана на C. Вообще я растерян, т.к. хэш-калькулятор видится небольшой программой, которая берёт файлы и пропускает их через математический алгоритм. Как открыть файл и вывести текст на экран известно уже несколько десятилетий. Да, имена файлов стали длиннее, диагонали мониторов больше, но принципиально ввод-вывод не изменился. Алгоритмы же и вовсе умещаются на листе бумаги — сегодня даже Blake3 можно выразить на [Javascript](https://emn178.github.io/online-tools/blake3/file/) и посчитать в браузере. Таким образом, от хэш-калькулятора, как и от обычного калькулятора (который можно написать даже на Basic под DOS) ожидаешь работы на самом широком спектре оборудования. Но именно ваш, Александр, калькулятор — из всех мне известных — является самым ~~капризным~~ требовательным до ресурсов. Вы это объясняете тем, что хотите считать хэш быстрее всех. А я прошу, условно говоря, добавить if <компьютер не самый современный и готов считать чуть-чуть-чуть медленее> then <использовать такой-то код>.

**Comment by aegoroff** [comment]
> [Zig](https://ziglang.org/)?

он самый. Да программа на C но, я использую Zig компилятор для кросс компиляции под линукс. Про все остальное мы вроде уже говорили, и я не вижу смысла повторяться.

> Александр, калькулятор — из всех мне известных — является самым капризным требовательным до ресурсов. 

про капризный вы точно загнули :) требование к процессору 10 летней давности не считаю чем-то из ряда вон выходящих. Простите.

**Comment by sergeevabc** [comment]
> Требование к процессору 10 летней давности не считаю чем-то из ряда вон выходящих.

Требование к оборудованию должно вытекать из функции. Если у нас есть код, выводящий Hello, world, скажем,

```c
#include <stdio.h>
int main(){puts("Hello, world!");}
```

то странно требовать современное железо для работы этого кода.

Так, наш соотечественник Дмитрий Дулесов написал [hashsum](https://github.com/ddulesov/hashsum) c Blake3 и GOST2012, T. Reichardt допилил 7-zip Игоря Павлова, добавив туда [Blake3](https://github.com/mcmilk/7-Zip-zstd/blob/master/C/hashes/blake3.c) на C, а M. Idrassi, создатель Veracrypt, придумал считать хэши (включая Blake3) не только для файлов, но и для папок с помощью его [dirhash](https://github.com/idrassi/DirHash). И все они считают быстро — без SSE4.

Просто вдумайтесь: игра Bioshock, оперирующая сложнейшими графическими функциями для имитации состояний морской воды, работает у меня на компьютере, а ваш консольный калькулятор — нет. Сюр и дичь!

**Comment by aegoroff** [comment]
Ну обсуждали же уже это 10 месяцев назад - зачем повторяться и терять время? В общем мой окончательный ответ - раззоритесь на процессор Intel Core 4 поколения (Haswell) или новее. Никаких сборок под старые процессоры я точно делать не буду - слишком много работы, для столь маленького профита. Я скорее заморочусь под ARM (перспектива), чем под то, что умрет в недалеком будущем.

**Comment by aegoroff** [comment]
сделано в https://github.com/aegoroff/hc/releases/tag/6.0.0rc2 для процессоров Core2 ссылка https://github.com/aegoroff/hc/releases/download/6.0.0rc2/hc-6.0.0rc2-x86_64-pc-windows-msvc-core2.tar.gz установщик, как для актуальной версии, делать не стал - думаю просто бинарика в архиве будет достаточно

**Comment by flawrist** [comment]
![](https://github.com/user-attachments/assets/f08b9f94-5d06-4208-9951-184719e4d316)

Информация о процессоре:
```
Name: Intel(R) Core(TM)2 Duo CPU     T7250  @ 2.00GHz
Vendor String: GenuineIntel
Vendor ID: Intel
PhysicalCores: 2
Threads Per Core: 1
Logical Cores: 2
CPU Family 6 Model: 15 Stepping: 13
Features: CMOV,CMPXCHG8,CX16,FXSR,FXSROPT,LAHF,MMX,NX,OSXSAVE,SSE,SSE2,SSE3,SSSE3,SYSCALL,SYSEE,VMX,X87,XSAVE
Microarchitecture level: 1
Cacheline bytes: 64
L1 Instruction Cache: 32768 bytes
L1 Data Cache: 32768 bytes
L2 Cache: 2097152 bytes
L3 Cache: 0 bytes
Frequency: 2000000000 Hz
```

**Comment by aegoroff** [comment]
@sergeevabc так, спасибо за инфу, буду смотреть

**Comment by aegoroff** [comment]
@sergeevabc Проблема не в CPU (-Dcpu=core2 тут ок) — Zig 0.16 тянет Win10 API. Проверяю, можно ли обойти жёсткую зависимость.

**Comment by aegoroff** [comment]
@sergeevabc увы но, - Zig 0.16 официально требует Windows ≥ 10 — это нельзя обойти флагом -Dcpu=core2. Поэтому тут я точно ничего не могу сделать

**Comment by flawrist** [comment]
Как я понимаю, последний Zig с поддержкой Windows 7 это 0.5.0, но ваш код уже использует более свежие фичи, поэтому скомпилировать даже с той версией тоже невозможно, верно?

**Comment by aegoroff** [comment]
да, верно. 0.5.0 это прямо совсем очень старое и по сути, переход на него, это полное переписывание, ибо даже при переходе с 0.15 на 0.16 пришлось много переделывать - там была сильно изменена стандартная библиотека (ввод/вывод, потоки и пр.). С 0.14 до 0.15 тоже были ломающие изменения, ну и так далее.
